// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPage(arg1, arg2) {
  return window['go']['main']['App']['GetPage'](arg1, arg2);
}

export function GetPageCount(arg1) {
  return window['go']['main']['App']['GetPageCount'](arg1);
}

export function SelectPdf() {
  return window['go']['main']['App']['SelectPdf']();
}
