// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPDF():Promise<string>;

export function OpenPDFMap(arg1:string):Promise<Array<main.PDFMapPage>>;

export function SaveCSV():Promise<void>;

export function SavePDFMap(arg1:Array<main.PDFMapPage>,arg2:string):Promise<void>;
