// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPage(arg1:string,arg2:number):Promise<Array<number>>;

export function GetPageCount(arg1:string):Promise<number>;

export function GetSettings():Promise<main.AppSettings>;

export function SelectPdf():Promise<string>;
