// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPage(arg1:string,arg2:number):Promise<Array<number>>;

export function GetPageCount(arg1:string):Promise<number>;

export function SelectPdf():Promise<string>;
